language: c

addons:
  homebrew:
    packages:
      - taglib
      - glib
      - libxml2
    update: true
  apt:
    packages:
      - libtagc0-dev
      - libcurl4-gnutls-dev

matrix:
  include:
    - name: macOS clang
      os: osx
      compiler: clang
    - name: Xenial clang
      os: linux
      dist: xenial
      compiler: clang
    - name: Xenial gcc
      os: linux
      dist: xenial
      compiler: gcc

script:
  - gem install mustache -v=0.7.0 && gem install ronn && autoreconf -fvi && ./configure && make all
  - make check
  - $TRAVIS_BUILD_DIR/src/castget -V
  - make clean
